repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
  - id: actionlint

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8  # Use the sha / tag you want to point at
  hooks:
  - id: clang-format
    args: ["-style=Google"]
