name: CMake Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Unixlike:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [release, debug]
        os: [ubuntu-latest]
        compiler: [gcc, clang]
    
    steps:
      - uses: actions/checkout@main
      
      - uses: lukka/get-cmake@a70f1cfa1857a3eecfe0d34962269e1b1e8be56c

      - name: Install dependency
        run: |
          sudo apt-get update
          sudo apt install libudev-dev
      
      - name: Configure CMake
        uses: lukka/run-cmake@2ce8982be71b8e9a3c4d5e432135035afd1e76a7
        with:
          configurePreset: unixlike-${{ matrix.compiler }}-${{ matrix.build_type }}
          buildPreset: unixlike-${{ matrix.compiler }}-${{ matrix.build_type }}
          
  Windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [release, debug]
        os: [windows-2019, windows-2022]
        platforms: [x64]
    
    steps:
      - uses: actions/checkout@main

      - uses: lukka/get-cmake@a70f1cfa1857a3eecfe0d34962269e1b1e8be56c

      - name: Configure CMake
        uses: lukka/run-cmake@2ce8982be71b8e9a3c4d5e432135035afd1e76a7
        with:
          configurePreset: ${{ matrix.os }}-${{ matrix.platforms }}-${{ matrix.build_type }}
          buildPreset: ${{ matrix.os }}-${{ matrix.platforms }}-${{ matrix.build_type }}
      
