name: CMake build test
run-name: 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Unixlike:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [release, debug]
        os: [ubuntu-latest]
        compiler: [gcc, clang]
    
    steps:
      - uses: actions/checkout@main
      
      - uses: lukka/get-cmake@latest
      
      - name: Configure CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: unixlike-${{ matrix.compiler }}-${{ matrix.build_type }}
          
  Windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [release, debug]
        os: [windows-2019, windows-2022]
        platforms: [x64]
    
    steps:
      - uses: actions/checkout@main

      - uses: lukka/get-cmake@latest

      - name: Configure CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.os }}-${{ matrix.platforms }}-${{ matrix.build_type }}
      
