name: Report Analysis

on: ["push"]

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: DMAHostRunner
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Configure code-analysis Preset
        uses: lukka/run-cmake@2ce8982be71b8e9a3c4d5e432135035afd1e76a7
        with:
          configurePreset: code-analysis
          buildPreset: code-analysis

      - name: Run clang-tidy
        run: |
          run-clang-tidy -clang-tidy-binary clang-tidy-18 -config-file clang-tidy-config -p ./build/code-analysis -j 4 | tee build/clang-tidy-output.txt

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@97bf5df3c09e75f5bcd72695998f96ebd701846e
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          clang-tidy-output: "build/clang-tidy-output.txt"
          upload: true

      - name: Run Unit Test
        run: |
          cd ./build/code-analysis/bin/
          ./dmatest
          cd -

      - name: Generate coverage info
        run: |
          cd ./build/code-analysis/bin/
          llvm-profdata merge -sparse default.profraw -o coverage.profdata
          llvm-cov export ./dmatese -instr-profile=coverage.profdata > coverage.json
          cd -

      - name: Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          fail_ci_if_error: true
          files: ./build/code-analysis/bin/coverage.json
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
