name: Report Analysis

on: ["push"]

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: DMAHostRunner
    steps:
      - name: Check git tokens
        run: |
          if [ -z "${{ secrets.CODACY_PROJECT_TOKEN }}" ]; then
            echo "Error: CODACY_PROJECT_TOKEN is not set"
            exit 1
          fi
          if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "Error: CODECOV_TOKEN is not set"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@main

      - name: Configure code-analysis Preset
        uses: lukka/run-cmake@2ce8982be71b8e9a3c4d5e432135035afd1e76a7
        with:
          configurePreset: code-analysis
          buildPreset: code-analysis

      - name: Run clang-tidy
        run: |
          run-clang-tidy -clang-tidy-binary clang-tidy-18 -config-file clang-tidy-config -p ./build/code-analysis -j 4 | tee build/clang-tidy-output.txt

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@97bf5df3c09e75f5bcd72695998f96ebd701846e
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          clang-tidy-output: "build/clang-tidy-output.txt"
          upload: true

      - name: Run Unit Test
        run: |
          cd ./build/code-analysis/bin/
          ./unittest
          cd -

      - name: Generate coverage info
        run: |
          cd ./build/code-analysis/bin/
          llvm-profdata merge -sparse default.profraw -o coverage.profdata
          llvm-cov export ./unittest -instr-profile=coverage.profdata -format=lcov > coverage.json
          cd -

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./build/code-analysis/bin/coverage.json

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          fail_ci_if_error: true
          files: ./build/code-analysis/bin/coverage.json
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
